# This is a basic workflow to help you get started with Actions

name: Dev Workflow

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: develop
  pull_request:
    branches: devlop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
          repository: Everevent-Kazedon-BE/security
          token: ${{ secrets.GH_TOKEN }} # `GH_PAT` is a secret that contains your PAT
          path: src/main/resources/config

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 16.0.2

      - name: Grant execute permisson for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}
        with:
          files: build/test-results/**/*.xml

      - name: Login to DockerHub
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_BACK_USERNAME }}
          password: ${{ secrets.DOCKERHUB_BACK_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_BACK_USERNAME }}/back:latest
